	library(openxlsx)
	library(dplyr)
	library(coalitions)
	library(jsonlite)
	library(reshape)
	library(doParallel)
	library(foreach)
	library(parallelsugar)
    library(ggplot2)
    library(pbapply)
    library(yaml)
	library(waffle)
	library(RColorBrewer)

