	library(openxlsx)
	library(dplyr)
	library(coalitions)
	library(jsonlite)
	library(reshape)
	library(doParallel)
	library(foreach)
	#library(devtools)
	#install_github('nathanvan/parallelsugar')
	library(parallelsugar)

    #library(dplyr)
    #library(ggthemes)
    library(ggplot2)
	#library(openxlsx)
    library(pbapply)
    library(yaml)
    #library(progress)