n_simulaciones: 100
n_cores: 10

coaliciones: 'Juani_2'

experiment_tag: 'experimento_016_Juani_2'

# Nuevos votos de Evopoli, se le roban a la UDI y RN.
# Elasticidades: 1 = udi + rn
elasticidad_evo_rn: 0.5
percentil_maximo_evo: 0.9
percentil_no2016_evo: 0.5
percentil_no2016_evo_lower: 0.25
percentil_no2016_evo_upper: 0.75

# Nuevos votos de JAK, se le roban a la UDI y RN
# Elasticidades: 1 = udi + rn
elasticidad_jak_rn: 0.4

# Máximo y minimo alcanzable en base a su elección presidencial
factor_ajuste_maximo_jak: 0.75
factor_ajuste_minimo_jak: 0.25

# Repartija del PRI
# 1 = rn + evo + dc
elesticidad_rn_pri: 0.3333
elesticidad_evo_pri: 0.3333

# Elasticidades RD
elasticidad_rd_ppd: 0.2
elasticidad_rd_ps: 0.2

# Movimiento DC
upper_dc: 1.1
lower_dc: 0.9

